### ISSUE TITLE
Lintian warning: desktop-mime-but-no-exec-code

### ISSUE THREAD

**Issue by hosiet** [linuxdeepin/deepin-draw#1]
There is a grammar mistake in `deepin-draw.desktop`. Please try to provide proper field code in `Exec=` key to reflect its working status.

Detailed descriptions can be found in [XDG Desktop Entry Specification](https://standards.freedesktop.org/desktop-entry-spec/latest/ar01s06.html).

P.S. Please also consider adding "Keywords=" key, which would stop lintian from complaining as well.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
