### ISSUE TITLE
打开大图片，绘图区不能适应图片大小

### ISSUE THREAD

**Issue by sonichy** [linuxdeepin/deepin-draw#13]
打开大尺寸图片，绘图区不能适应图片大小，造成导出图片只有一部分。

**Comment by wythe0701** [comment]
当前画板功能设定是在已打开画板的情况下不会适应图片大小，主要是考虑不要修改当前已设定画布大小；
当前问题可以2方法处理：
1、右键打开大分尺寸图片（会自动适应图片大小）；
2、通过裁剪工具修改画板大小；
