### ISSUE TITLE
Drawn lines does not stack up

### ISSUE THREAD

**Issue by vesterlay** [linuxdeepin/deepin-draw#14]
This is also an issue with ScreenShot. I really like an idea of being able to grab everything you've drawn, but current implementation is bad in my opinion. I suggest splitting this functionality into another tool. Right now when I want to draw a heart for example, I can't because when I do one side I can't the other. The app wrongly assumes I want to grab a side I've already drawn. It's quite infuriating. 

Another annoying thing is when I select a tool "Draw a line" and can draw only one line, because application instantly comes back to area select.

**Comment by wythe0701** [comment]
Thank you for your question. We are redesigning the drawing function (separation of drawing and selection function) to prevent wrong selection in continuous drawing.

**Comment by deepin-CD** [comment]
This issue will be temporarily closed due to no response received. Please reopen the issue if there're any new updates.
