### ISSUE TITLE
Unable to Install ...

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/deepin-draw#2]
Hello,

**I was surprised this application wasn't part of the pre-installed with Deepin 15.5**

**I tried** '`sudo apt-get install deepin-draw`' **... but package not found ... an even bigger surprise ...**

I thought i'll build it and install ... facing the following error ...

```
../../deepin-draw-1.0.0/utils/imageutils_freeimage.h:2:23: fatal error: FreeImage.h: No such file or directory
 #include <FreeImage.h>
                       ^
compilation terminated.
Makefile:1229: recipe for target 'imageutils.o' failed
make: *** [imageutils.o] Error 1

```

shouldn't installation(by way of apt installs or for that matter building from source) of deepin apps be the easiest and quickest in the latest Deepin OS ?

i don't understand i have hardly been able to build and install any of the apps i have tried successfully ... 

Just like the many other deepin applications ... I feel you SHOULD create an application that takes care of such an issue ... may be like a **'deepin-build-esssentials'** ... it will surely save a lot of trouble for anybody who wants to compile and install 'deepin' packages from source without any installation and dependency problems.

**Comment by pangpangpang3** [comment]
You need install : ,libfreeimage-dev

**Comment by aiamuzz** [comment]
installed ... libfreeimage-dev ...

following error while trying to build ... last few lines of the command '`qmake ..`'

```
process translations/deepin-draw_uk.ts
Updating 'translations/deepin-draw_uk.qm'...
    Generated 59 translation(s) (59 finished and 0 unfinished)
    Ignored 29 untranslated source text(s)

process translations/deepin-draw_zh_CN.ts
Updating 'translations/deepin-draw_zh_CN.qm'...
    Generated 88 translation(s) (88 finished and 0 unfinished)
Project ERROR: dtkwm development package not found
AH-21:~/Downloads/linuxPackagesBuildnInstall/deepin-draw-1.0.0/build$ make
make: *** No targets specified and no makefile found.  Stop.

```

**Comment by zhtengw** [comment]
You need libdtkwm-dev now.

Best Regards,
Aten Zhang

**Comment by pangpangpang3** [comment]
The backend dependencies of the warehouse may not be added during the internal test.
