### ISSUE TITLE
Font size is not saved

### ISSUE THREAD

**Issue by DmitrySkibitsky** [linuxdeepin/deepin-draw#3]
Font size is not saved

```bash
>>> yaourt deepin-draw                                               
community/deepin-draw 1.0.0-2 (deepin-extra) [installed]
```

![ezgif-1-6261ca4c0e5a](https://user-images.githubusercontent.com/20288556/49908876-1880cd80-fe85-11e8-9e71-8d0b8bf96561.gif)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
