### ISSUE TITLE
[Feature Request] Copy as Image to Clipboard

### ISSUE THREAD

**Issue by iamhyc** [linuxdeepin/deepin-draw#9]
**Description**:
When select objects in deepin-draw, in addition to internally handling "Copy" action, further compose the objects as an image (with the boundingRect size) copied into clipbaord.
（当选中deepin-draw中的对象时，除了在内部响应“复制”操作，同时把选中的对象生成 以bounding box为边界 的图像，并复制到剪贴板中）

**Reason**:
It would be very useful to directly export the image at its original resolution.
（非常便捷，直接导出原始分辨率）

@z966768

**Comment by xmuli** [comment]
@deepin-CD

**Comment by iamhyc** [comment]
@deepin-CD 可以回复一下吗？

**Comment by iamhyc** [comment]
@deepin-CD @xmuli @z966768

**Comment by deepin-CD** [comment]
@iamhyc 当选中deepin-draw中的对象时，是将当前对象信息拷贝到剪切板，如果复制位图会导致失去复制矢量对象功能

**Comment by iamhyc** [comment]
> @iamhyc 当选中deepin-draw中的对象时，是将当前对象信息拷贝到剪切板，如果复制位图会导致失去复制矢量对象功能

是的，但是这样可以提供快捷的图像导出，而且看起来增加这个实现没有难度

**Comment by deepin-CD** [comment]
@iamhyc 设计拷贝时不止矢量对象，还会涉及到从外部拷贝数据（如：文字），存在2套逻辑会导致功能错乱

**Comment by iamhyc** [comment]
> @iamhyc 设计拷贝时不止矢量对象，还会涉及到从外部拷贝数据（如：文字），存在2套逻辑会导致功能错乱

据我所了解，clipboard的mimedata没有所谓“矢量对象”定义，所以我上面是说内部实现。

重新整理一下我的需求的逻辑：
- 内部 --> 内部：拷贝不要依赖clipboard
- 外部 --> 内部：自然的，使用clipboard中的mimedata
- 内部 --> 外部：在做内部拷贝时，“合理地”拷贝到clipboard
（如果矢量对象是文字，对应到text；如果是其他，pixmap对应到imageData）

我还没有去看deepin-draw的代码，但试了一下，似乎现在没有实现任何 “内部 --> 外部”的拷贝，所以不太清楚所说的“两套逻辑”是什么意思？

**Comment by iamhyc** [comment]
@deepin-CD hello，我按照上面的思路做了个分离的实现，简单测试了下没问题，麻烦看一下能不能merge，谢谢

https://github.com/iamhyc/deepin-draw/commit/167870d826347e529c5beff8ca63996052663d3a

**Comment by iamhyc** [comment]
@deepin-CD 服了你们了，无话可说

**Comment by deepin-CD** [comment]
@iamhyc 查看你的提交，通过拷贝数据类型就可以区分"内-->内" 和 "外-->内" 的拷贝逻辑，无需添加逻辑

**Comment by iamhyc** [comment]
@deepin-CD 你们现在这个实现是不对的，我只是陈述这个事实；最后：talk is cheap, show me your code.

**Comment by iamhyc** [comment]
为了避免你们不知道自己的实现有多蠢，这里举了几个小例子，https://bbs.deepin.org/post/207663

这个issue没必要回复了，如果你们真的有诚意，早干什么去了……
